// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_kanban.cpp"
#include "EWIEGA46WW/moc_login.cpp"
#include "EWIEGA46WW/moc_taskdelegate.cpp"
#include "EWIEGA46WW/moc_taskeditor.cpp"
#include "EWIEGA46WW/moc_tasklist.cpp"
