name: GitHub Actions Demo
on: [push]

#defaults:
#  run:
#    working-directory: scripts

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh .scripts/formatting.sh